//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.16 at 12:47:42 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Holiday", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.jollyday.config;
